export const FETCH_PERMISSIONS_PENDING =
  "@@permissions/FETCH_PERMISSIONS_PENDING";
export const FETCH_PERMISSIONS_FAILURE =
  "@@permissions/FETCH_PERMISSIONS_FAILURE";
export const FETCH_PERMISSIONS_SUCCESS =
  "@@permissions/FETCH_PERMISSIONS_SUCCESS";
