export const FETCH_THREAD_FAILURE = "@@discussion/FETCH_THREAD_FAILURE";
export const FETCH_THREAD_SUCCESS = "@@discussion/FETCH_THREAD_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "@@discussion/FETCH_COMMENTS_FAILURE";
export const FETCH_COMMENTS_SUCCESS = "@@discussion/FETCH_COMMENTS_SUCCESS";
