const FETCH_THREAD_FAILURE = "FETCH_THREAD_FAILURE";
const FETCH_THREAD_SUCCESS = "FETCH_THREAD_SUCCESS";
const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
