import { GridColDef } from "@mui/x-data-grid";
import { ReferenceItemDataType } from "./context/ReferencesTabContext";

export const columns: GridColDef[] = [
  { field: "id", headerName: "", width: 0 },
  { field: "title", headerName: "Title", width: 320 },
  { field: "authors", headerName: "Authors", width: 280 },
  { field: "last_author", headerName: "Last Author", width: 140 },
  {
    field: "hubs",
    headerName: "Hubs",
    description: "This is Hub Column",
    sortable: false,
    width: 240,
    // TODO: calvinhlee - investigate what this is
    // valueGetter: (params: GridValueGetterParams) =>
    //   `${params.row.firstName || ""} ${params.row.lastName || ""}`,
  },
  {
    field: "published_date",
    headerName: "Publication Date",
    type: "string",
    width: 180,
  },
  {
    field: "published_year",
    headerName: "Publication Year",
    type: "string",
    width: 120,
  },
];

export const rows: ReferenceItemDataType[] = [
  {
    id: 0,
    authors: "Patrick Matalla et al.",
    hubs: "Optics",
    last_author: "Christian Koos",
    published_date: "Oct 13, 2023",
    published_year: "2023",
    title: "Visual Prompting via Imagie Inpaining",
  },
  {
    id: 1,
    authors: "Ingrid Bretherton et al.",
    hubs: "Computer Engineering",
    last_author: "Ada Cheung",
    published_date: "Jan 11, 2021",
    published_year: "2021",
    title: "Hardware Compairson of Feed-Forward Clock Recovery",
  },
  {
    id: 2,
    authors: "Thomas Clarke et al.",
    hubs: "Medicine",
    last_author: "Johnathan Whetstine",
    published_date: "July 8, 2022",
    published_year: "2022",
    title: "Histon Lysine Methylation Dynamics Control",
  },
  {
    id: 3,
    authors: "Thierry Zami et al.",
    hubs: "Computer Science",
    last_author: " Bruno Lavigne",
    published_date: "May 7, 2013",
    published_year: "2013",
    title: "Impact of Crosstalk on 800 Gb/s",
  },
  {
    id: 4,
    authors: "Patrick Matalla et al.",
    hubs: "Optics",
    last_author: "Christian Koos",
    published_date: "Oct 13, 2023",
    published_year: "2023",
    title: "Visual Prompting via Imagie Inpaining",
  },
  {
    id: 5,
    authors: "Ingrid Bretherton et al.",
    hubs: "Computer Engineering",
    last_author: "Ada Cheung",
    published_date: "Jan 11, 2021",
    published_year: "2021",
    title: "Hardware Compairson of Feed-Forward Clock Recovery",
  },
  {
    id: 9,
    authors: "Ingrid Bretherton et al.",
    hubs: "Computer Engineering",
    last_author: "Ada Cheung",
    published_date: "Jan 11, 2021",
    published_year: "2021",
    title: "Hardware Compairson of Feed-Forward Clock Recovery",
  },
  {
    id: 10,
    authors: "Ingrid Bretherton et al.",
    hubs: "Computer Engineering",
    last_author: "Ada Cheung",
    published_date: "Jan 11, 2021",
    published_year: "2021",
    title: "Hardware Compairson of Feed-Forward Clock Recovery",
  },
  {
    id: 6,
    authors: "Ingrid Bretherton et al.",
    hubs: "Computer Engineering",
    last_author: "Ada Cheung",
    published_date: "Jan 11, 2021",
    published_year: "2021",
    title: "Hardware Compairson of Feed-Forward Clock Recovery",
  },
  {
    id: 7,
    authors: "Ingrid Bretherton et al.",
    hubs: "Computer Engineering",
    last_author: "Ada Cheung",
    published_date: "Jan 11, 2021",
    published_year: "2021",
    title: "Hardware Compairson of Feed-Forward Clock Recovery",
  },
  {
    id: 8,
    authors: "Ingrid Bretherton et al.",
    hubs: "Computer Engineering",
    last_author: "Ada Cheung",
    published_date: "Jan 11, 2021",
    published_year: "2021",
    title: "Hardware Compairson of Feed-Forward Clock Recovery",
  },
];
