export const VALIDATION_STATE = {
  DENIED_TOO_MANY_ATTEMPS: "DENIED_TOO_MANY_ATTEMPS",
  DENIED_WRONG_USER: "DENIED_WRONG_USER",
  LOADING: "LOADING",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  VALIDATED: "VALIDATED",
};
