FROM node:14.15.5-alpine

# install dependencies
RUN apk add --no-cache --virtual .build-deps \
    git \
    python \
    make \
    g++

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
COPY yarn.lock /usr/src/app
COPY .sentryclirc /usr/src/app
COPY .npmrc /usr/src/app
COPY tsconfig.json /usr/src/app

# install yarn and yarn install
RUN yarn install --production --no-progress

# Expose the public http port
EXPOSE 3000

# Set env variables.
# FIXME: This needs to move to a more secure location
ENV GOOGLE_CLIENT_ID=192509748493-3enrmve4vlikpff88lujns7b4d72hgbg.apps.googleusercontent.com
ENV ORCID_CLIENT_ID=APP-28GINQJPUWS3ZTW1
ENV ORCID_KID=production-orcid-org-7hdmdswarosg3gjujo8agwtazgkp1ojs
ENV WEB3_INFURA_PROJECT_ID=a7ccde5d021c48e1a0525dfd6e58490f
ENV RECAPTCHA_CLIENT_KEY=6LdxeboZAAAAAEgn_Oa0VnohS724vZhI3_ezLbVD
ENV SIFT_BEACON_KEY=b27b7ee421
ENV ELASTIC_APM_URL=https://d11bb2079f694eb996ddcfe6edb848f7.apm.us-west-2.aws.cloud.es.io:443
ENV GA_TRACKING_ID=UA-106669204-1

# Bundle app source
COPY . /usr/src/app
ARG REACT_APP_ENV
ENV REACT_APP_ENV=$REACT_APP_ENV
ARG SENTRY_RELEASE
RUN SENTRY_RELEASE=${SENTRY_RELEASE} REACT_APP_ENV=${REACT_APP_ENV} yarn run build
RUN SENTRY_RELEASE=${SENTRY_RELEASE} yarn run sentry;

# build and Start server
CMD ["yarn", "start"]
