export const DEFAULT_SUMMARY = {
  blocks: [
    {
      key: "ro52",
      data: { "text-align": "start" },
      text: "Summary",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [
        { style: "fontsize-24", length: 7, offset: 0 },
        { style: "BOLD", length: 7, offset: 0 },
      ],
    },
    {
      key: "863i4",
      data: {},
      text: "What is the paper trying to solve?",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [
        { style: "color-rgb(0,0,0)", length: 34, offset: 0 },
        { style: "fontsize-medium", length: 34, offset: 0 },
        { style: "fontfamily-Times", length: 34, offset: 0 },
        { style: "fontsize-16", length: 34, offset: 0 },
      ],
    },
    {
      key: "8ndmj",
      data: { "text-align": "start" },
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "am12r",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "1evak",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "368i5",
      data: {},
      text: "Results",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [
        { style: "fontsize-24", length: 7, offset: 0 },
        { style: "BOLD", length: 7, offset: 0 },
      ],
    },
    {
      key: "855or",
      data: {},
      text: "What conclusion did the paper come to, how did it get there?",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [
        { style: "color-rgb(0,0,0)", length: 60, offset: 0 },
        { style: "fontsize-medium", length: 60, offset: 0 },
        { style: "fontfamily-Times", length: 60, offset: 0 },
        { style: "fontsize-16", length: 60, offset: 0 },
      ],
    },
    {
      key: "3rc38",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "6fdfp",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "agkvq",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "et9ao",
      data: {},
      text: "Significance",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [
        { style: "BOLD", length: 12, offset: 0 },
        { style: "fontsize-24", length: 12, offset: 0 },
      ],
    },
    {
      key: "c79mq",
      data: {},
      text:
        "How does the paper help our previous understanding, where do we go from here? Is there any impact this can have on specific industries?",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [
        { style: "color-rgb(0,0,0)", length: 135, offset: 0 },
        { style: "fontsize-medium", length: 135, offset: 0 },
        { style: "fontfamily-Times", length: 135, offset: 0 },
        { style: "fontsize-16", length: 135, offset: 0 },
      ],
    },
    {
      key: "7trqc",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "clog9",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "bl7ok",
      data: {},
      text: "",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
    {
      key: "3tbta",
      data: {},
      text: "\n",
      type: "unstyled",
      depth: 0,
      entityRanges: [],
      inlineStyleRanges: [],
    },
  ],
  entityMap: {},
};
