export type STEP =
  | "INTRO"
  | "CONTENT"
  | "AUTHORS_AND_METADATA"
  | "DECLARATION"
  | "PREVIEW"
  | "SUCCESS";

export const ORDERED_STEPS: STEP[] = [
  "INTRO",
  "CONTENT",
  "AUTHORS_AND_METADATA",
  "DECLARATION",
  "PREVIEW",
  "SUCCESS",
];
