export type STEP =
  | "INTRO_PUBLISH_IN_JOURNAL"
  | "INTRO_PUBLISH_RESEARCH"
  | "CONTENT"
  | "AUTHORS_AND_METADATA"
  | "DECLARATION"
  | "PREVIEW"
  | "SUCCESS";

export type ACTION = "PUBLISH_IN_JOURNAL" | "PUBLISH_RESEARCH" | "PUBLISH_NEW_VERSION";

export const ORDERED_STEPS: STEP[] = [
  "INTRO_PUBLISH_IN_JOURNAL",
  "INTRO_PUBLISH_RESEARCH",
  "CONTENT",
  "AUTHORS_AND_METADATA",
  "DECLARATION",
  "PREVIEW",
  "SUCCESS",
];
