export const GET_AUTHOR = "@@author/GET_AUTHOR";
export const SAVE_AUTHOR_CHANGES = "@@author/SAVE_AUTHOR_CHANGES";
export const GET_AUTHORED_PAPERS_PENDING =
  "@@author/GET_AUTHORED_PAPERS_PENDING";
export const GET_AUTHORED_PAPERS_FAILURE =
  "@@author/GET_AUTHORED_PAPERS_FAILURE";
export const GET_AUTHORED_PAPERS_SUCCESS =
  "@@author/GET_AUTHORED_PAPERS_SUCCESS";

export const GET_USER_DISCUSSIONS_PENDING =
  "@@author/GET_USER_DISCUSSIONS_PENDING";
export const GET_USER_DISCUSSIONS_FAILURE =
  "@@author/GET_USER_DISCUSSIONS_FAILURE";
export const GET_USER_DISCUSSIONS_SUCCESS =
  "@@author/GET_USER_DISCUSSIONS_SUCCESS";

export const GET_USER_CONTRIBUTIONS_PENDING =
  "@@author/GET_USER_CONTRIBUTIONS_PENDING";
export const GET_USER_CONTRIBUTIONS_FAILURE =
  "@@author/GET_USER_CONTRIBUTIONS_FAILURE";
export const GET_USER_CONTRIBUTIONS_SUCCESS =
  "@@author/GET_USER_CONTRIBUTIONS_SUCCESS";
export const UPDATE_AUTHOR_BY_KEY = "@@author/UPDATE_AUTHOR_BY_KEY";
