export const GET_AUTHOR = "@@author/GET_AUTHOR";
export const GET_AUTHORED_PAPERS_PENDING =
  "@@author/POST_PAPER_SUMMARY_PENDING";
export const GET_AUTHORED_PAPERS_FAILURE =
  "@@author/POST_PAPER_SUMMARY_FAILURE";
export const GET_AUTHORED_PAPERS_SUCCESS =
  "@@author/GET_AUTHORED_PAPERS_SUCCESS";
